# Generated by Django 4.1 on 2024-05-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
